### ISSUE TITLE
drop out participants freezes the tournament

### ISSUE THREAD

**Issue by prof-a-schmidt** [Moritz72/ToMaChess#4]
Wenn man (bei einem Keizer-Turnier, weiß nicht ob das relevant ist) einen Spieler entfernt, so ändert sich die angezeigte Anzahl der Teilnehmer nicht und das Turnier kann nicht mehr geöffnet werden. (win10, 64bit)

**Comment by Moritz72** [comment]
Die angezeigte Anzahl an Teilnehmern ändert sich beim Teilnehmer ausschließen nicht. Die Teilnehmer sind dann auch immer noch in der Tabelle zu sehen, aber werden nur nicht mehr gepaart.

Aber dass das Turnier nicht mehr geöffnet werden kann ist komisch. Ich hab gerade mal ein bisschen rumprobiert und bei mir funktioniert alles. Kannst du mir ein paar mehr Infos geben? Passiert es auch bei anderen Turniervarianten? Welche Version benutzt du? usw.

**Comment by prof-a-schmidt** [comment]
Mmh. Mir ist das mit realen Spielerdaten bei einem realen Turnier passiert. Habe gerade ein Keizer-Turnier mit erfundenen Nutzernamen erstellt und leider trat der Effekt dabei nicht auf. Werde weiter versuchen, den Fehler stabil zu reproduzieren.

**Comment by prof-a-schmidt** [comment]
So jetzt (ToMaChess v1.2.0 unter win10 64bit). Der Effekt tritt rekonstruierbar auf, wenn man einen Spieler ausschließt, der bei einer der vorangegangenen Runden ein bye hatte. (Insofern ein Problem, dass bei anderen Turnieren als Keizer nicht auftritt.)

**Comment by Moritz72** [comment]
Ich habe den Bug jetzt gefixed. Partien gegen einen Spieler der ausgeschlossen wurde zählen jetzt wie ein bye, was auch schon vorher mehr oder weniger aus Versehen der Fall war.

Das Turnier sollte sich jetzt in der neuen Version auch wieder öffnen lassen.

**Comment by prof-a-schmidt** [comment]
Danke! Leider kann ich es nicht ausprobieren, weil der win10 Virenscanner beim Versuch, Version 1.2.1 zu installieren interveniert. Keine Möglicheit die Installation auf Rückfrage zu erlauben, sogar die Installationsdatei wird ungefragt gelöscht. Ziemlich sicher ein Microsoft-Problem. Hoffentlich löst sich das Problem bei einem der folgenden MS-Updates wieder auf.

**Comment by prof-a-schmidt** [comment]
So, MS hatte ein Einsehen und ich konnte nun Version 1.2.1 installieren. Funktioniert! Danke nochmal.
